### ISSUE TITLE
BUG: Odd Behavior When Using Telescope to Search for Bookmarks

### ISSUE THREAD

**Issue by andysazima** [EvWilson/spelunk.nvim#7] opened 2024-11-05 21:21 UTC
There is an odd behavior with Spelunk's Telescope extension that I don't see in other Telescope extensions.

## Description

When you use the Spelunk Telescope extension and search for a bookmark, each time it fuzzy finds a new character that is included in the results names, it will move the cursor from the end back 1 character. If you move the cursor back to the end, then add another character that will be fuzzy found by Telescope, the cursor will move to the left 1 character. After moving to the left 1 character, it won't move anymore.

## How to Reproduce:

1. Put some bookmarks in the stack

![image](https://github.com/user-attachments/assets/f2ce724f-f995-46ee-9278-1906c5bbb762)

2. Open the Spelunk Telescope extension (default `<leader>bf`)

![image](https://github.com/user-attachments/assets/dd60ebe2-057c-4bff-9d94-d79f37624c1c)

3. Type a character that will guaranteed be found in the bookmarks list by Telescope

![image](https://github.com/user-attachments/assets/0dc56bcf-641e-4f03-9253-fdb85382392d)

Note that now the cursor was moved one character to the left. If you move the cursor back to the end, then type another character that will be found by Telescope, the cursor will move back to the left by 1 character.

Additional steps can be done for additional odd behavior

4. Add more than 2 characters that will be found by Telescope
5. Add a character(s) that will make the search turn up no results by Telescope (e.g. type a string of numbers or symbols)

![image](https://github.com/user-attachments/assets/0332d87f-67d4-47a6-adc8-a17ea5b54468)

6. Delete the characters one by one until you reach a string that will be found by Telescope

![image](https://github.com/user-attachments/assets/7004f886-4f9c-4f30-bcb3-6f3460d09944)

Note that once the string is gives us a result in Telescope, the cursor will be moved left by 1 character.

## Neovim Info

Version: 0.10.1
Other Extensions: Lazy, Plenary, Telescope, Spelunk

This bug was tested only with the necessary extensions for Spelunk to work.

**Comment by EvWilson** [comment] 2024-11-05 21:24
Thank you so much for the bug report! What a strange one. I was able to reproduce from within my setup, so I'll try to get around to looking into it in the next couple days.

**Comment by andysazima** [comment] 2024-11-05 21:37
Note that it also happens in the stack search too. Thanks for taking a look!

**Comment by EvWilson** [comment] 2024-11-05 23:47
Hey @andysazima! I think I've tackled the issue over on the `telescope-cursor-issue` branch. Going to merge this in within the next hour or so probably, just wanting to test it with larger issues to make sure the problem is well and truly gone, and not causing any OBOE issues.

**Comment by EvWilson** [comment] 2024-11-06 00:38
Fix should be merged! I'll leave this issue open for a day or so, in case it's still present - but by my testing we should be all good to go!

**Comment by EvWilson** [comment] 2024-11-06 19:02
Thanks so much for your help with the project, hope you enjoy the plugin!

**Closed by EvWilson** 2024-11-06 19:02 UTC
